### ISSUE TITLE
featuresAt discontinued?

### ISSUE THREAD

**Issue by joaogarin** [mapbox/analysis-demos#14]
Hello,

I am trying to replicate the nyc app with recent versions of mapbox, however It looks like the function featuresAt is not present in newer versions of the map. Is this true? If so, is there a replacement?

Best regards
Joao Garin

**Comment by hugotox** [comment]
https://www.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/

**Comment by danswick** [comment]
Thanks for the comment, @hugotox. featuresAt has been replaced with [queryRenderedFeatures](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures). 

Sounds like we're good to close here.
