### ISSUE TITLE
Mapbox style deleted

### ISSUE THREAD

**Issue by 0x7b1** [mapbox/analysis-demos#15]
Hi,

I was playing around and realised that the demo "nyc-attractions" is no longer loading the style `mapbox://styles/mapbox/cika7lsg6003p9fm1y5eet742` because it seems to was deleted. Please could you reupload? 
Thank you

**Comment by wilsotc** [comment]
The mapbox style isn't deleted, but the accessToken being used causes the backend service to throw a 404. You can see the style using an alternate URL:
https://api.mapbox.com/styles/v1/mapbox/cika7lsg6003p9fm1y5eet742?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpbG10dnA3NzY3OTZ0dmtwejN2ZnUycjYifQ.1W5oTOnWXQ9R1w8u3Oo1yA

**Comment by 0x7b1** [comment]
Thank you :)

**Comment by 0x7b1** [comment]
Thank you :)

**Comment by blaze515** [comment]
Hi. I'm also getting this error:

`"message": "Style not found"`

I have tried using my access key. The link above also is giving an access denied error.

I have also tried replacing line 61 in the index.js file with a new style:

`  style: 'mapbox://styles/mapbox/light-v9',`

but this seems to be causing other errors.
