### ISSUE TITLE
Travel industry demo

### ISSUE THREAD

**Issue by tatsvc** [mapbox/analysis-demos#2]
We're [building out a new industry page](https://github.com/mapbox/www.mapbox.com/issues/6718) for the travel industry that we can use for outbounds. It would be great if we can have a demo app that shows off what's possible with Mapbox.

**Timeline**: any time between now and 2nd week of march

**Comment by tristen** [comment]
@noemiwalzebuck I heard a rumour you might be able to help procure data? Ideally we pull some creative commons source of hotel/resort locations complete with pictures.
