### ISSUE TITLE
Can´t modify correctly geojson data

### ISSUE THREAD

**Issue by micmicto** [mapbox/analysis-demos#4]
Hi. And sorry. I´m new with Mapbox and code... and all. But I really what to make a map similar to nyc-attractions. Someone know why if I change de data of art_galleries.geojson file and tried to run the complete map... The art galleries continue appear in the same place although I deleted them. And the points of my geojson doesn't appear. :cry: I tried to modify another of the files and now... all the points (even those I not modified) disappeared :disappointed: 

I think it might be related to the "Running locally" and "Building" but... I couldn´t understand these requirements.

:sweat_smile:

**Comment by MappingKat** [comment]
Did you figure this out?  If you make changes you need to build again so that it grabs the changes in bundle.js.  I discovered that it does not work with the mapbox id beforehand.  It solely needs to be `npm run build`.
