### ISSUE TITLE
MapboxAccessToken=<YOUR TOKEN> npm start

### ISSUE THREAD

**Issue by rimaaii** [mapbox/analysis-demos#8]
Hello,

how could I update the API token? I installed the app but cannot run this line
MapboxAccessToken=<YOUR TOKEN> npm start

Because MapboxAccessToken is not recognized as an internal or external command. I can npm start but the API token is missing.

Thanks for your advice.

**Comment by danswick** [comment]
Hi @rimaaii, 

Make sure `MapboxAccessToken=<YOUR TOKEN> npm start` is all in the same command and that you've substituted a valid [access token](https://www.mapbox.com/help/define-access-token/) for `<YOUR TOKEN>`.
